#!/bin/sh

set -e

script/bootstrap
bundle exec jekyll build
bundle exec htmlproofer ./_site --check-html --check-sri --allow-hash-href --url-ignore "/tags,/about"
bundle exec rubocop -D --config .rubocop.yml
bundle exec script/validate-html
gem build jekyll-theme-architect.gemspec
